version: '3.8'

services:
  gateway:
    build: .
    container_name: safescan_gateway
    ports:
      - "8083:80"
    networks:
      - safescan-network
    restart: unless-stopped

networks:
  safescan-network:
    external: true
