version: '3.8'

services:
  gateway:
    build: .
    ports:
      - "80:80"
    depends_on:
      - safescan_apis
      - safescan_webapp
      - safescan_monitoring
    networks:
      - safescan-network
    restart: unless-stopped

networks:
  safescan-network:
    external: true
